3461/curators can see the feature dashboard
Cyber4All/clark-client pull request #1121
Opened 2021-01-22 17:39 UTC by EVogel1999

This PR makes the feature dashboard option in the navbar invisible to everyone who isn't an admin.  Completes story [3461 - Curators can see the feature dashboard](https://app.clubhouse.io/clarkcan/story/3461/curators-can-see-the-feature-dashboard).

2021-01-25 13:04 UTC, Cwagne17 approved these changes

2021-01-25 13:04 UTC, pzalep1 requested changes

2021-01-25 13:04 UTC, pzalep1 commented on src/app/core/auth.service.ts
> +    return this.group.value === AUTH_GROUP.ADMIN;
Editors also have the ability to feature learning objects.

2021-01-26 15:53 UTC, pzalep1 approved these changes

2021-01-26 17:48 UTC, merged