Integrate Standard Guidelines into Client
Cyber4All/clark-client pull request #1178
Opened 2021-08-16 16:50 UTC by Cwagne17

PR completest the work on clark-client [Story 5026](https://app.clubhouse.io/clarkcan/story/5026/integrate-standard-guidelines-into-client). 

Changes standard-outcomes -> guidelines 
Implements new routes, and uses the seraching routes.

2021-08-16 18:18 UTC, pzalep1 requested changes
This looks great! Just two small changes.

2021-08-16 18:18 UTC, pzalep1 commented on src/entity/guideline/error-messages.ts
> +  INVALID_YEAR: 'Year must bea defined non-empty string.',
```suggestion
  INVALID_YEAR: 'Year must be a defined non-empty string.',
```

2021-08-16 18:18 UTC, pzalep1 commented on src/entity/guideline/guideline.ts
> +  private copyOutcome(outcome: any): void {
Could we change this to guideline to match the rest of the entity?

2021-08-16 19:26 UTC, EVogel1999 approved these changes
Good job!  Looks great!  Thank you for renaming standard-outcomes to guidelines.

2021-08-17 12:57 UTC, mfranz1 approved these changes

2021-08-17 14:20 UTC, jouypo23 approved these changes

2021-08-19 12:45 UTC, pzalep1 approved these changes

2021-08-19 13:23 UTC, merged