Relevacny builder module
Cyber4All/clark-client pull request #1180
Opened 2021-08-19 19:56 UTC by mfranz1

2021-08-20 12:44 UTC, pzalep1 requested changes

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/learning-object-builder/learning-object-builder.component.html
> -  <onion-builder-navbar *ngIf="true" [adminMode]="adminMode"></onion-builder-navbar>
This should probably stay.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/admin/components/learning-object-list-item/learning-object-list-item.component.html
> +      <li [routerLink]="['/onion/relevancy-builder', learningObject.id]"><i class="far fa-puzzle-piece"></i>Object Relevancy</li>
Can we say Map and Tag?

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/builder-store.service.ts
> +  ADD_FILE_META,
I think we can get rid of all the stuff that isn't used in this builder.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/components/builder-navbar/builder-navbar.component.html
> +      <!-- update routerLinkActive with class used to show that link is active -->
Remove commented code.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/components/builder-navbar/builder-navbar.component.ts
> +  buildTooltip() {
Do we still need this function?

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/components/outcome/outcome-typeahead/outcome-typeahead.component.html
> +    <span *ngIf="goodVerb">
Remove commented code.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/components/scafold/scafold.component.html
> +      <!-- <div class = "info">
Remove commented code.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/relevancy-builder.component.ts
> +            if (learningObject.status === LearningObject.Status.RELEASED) {
All learning objects that are not unreleased can be loaded in here so we should make sure we're not throwing people out of the builder.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/relevancy-builder.component.ts
> +import { takeUntil } from 'rxjs/operators';
All unecessary code should be taken out of this file as well.

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/relevancy-builder.routing.ts
> +      { path: 'mappings', component: OutcomePageComponent, data: { state: 'outcomes' } },
What is this route for?

2021-08-20 12:44 UTC, pzalep1 commented on src/app/onion/relevancy-builder/validators/learning-object.validator.ts
> +import { Injectable } from '@angular/core';
All unnecessary code should be removed from this file as well.

2021-08-23 13:17 UTC, mfranz1 commented on src/app/onion/learning-object-builder/learning-object-builder.component.html
> -  <onion-builder-navbar *ngIf="true" [adminMode]="adminMode"></onion-builder-navbar>
Good catch, my bad

2021-08-30 14:17 UTC, Cwagne17 approved these changes

2021-08-30 18:18 UTC, EVogel1999 requested changes
Just a few comments about styling.  Also just going to put what we talked about this morning in here:

- Fix the standard search to auto-suggest when an outcome is selected

2021-08-30 18:18 UTC, EVogel1999 commented on src/app/admin/components/filter-search/filter-search.component.ts
> +  @Output() topicFilter = new EventEmitter<any[]>();
Lets add a type to this

2021-08-30 18:18 UTC, EVogel1999 commented on src/app/core/relevancy.service.ts
> +  async updateObjectTopics(username: string, id: string, topicIds: string[]): Promise<void> {
These should have block comments.

2021-08-30 18:18 UTC, EVogel1999 commented on src/app/onion/relevancy-builder/components/outcome/outcome.component.scss
> +    background: #f8f9fd;
This should be a standard color.

2021-08-30 18:18 UTC, EVogel1999 commented on src/app/onion/relevancy-builder/components/standard-outcomes/outcome-list-item/outcome-list-item.component.scss
> +    box-shadow: inset 0 2px 6px 2px rgba(0, 0, 0, 0.1);
The colors in this file should be standard colors.

2021-08-31 17:08 UTC, jouypo23 approved these changes

2021-09-01 18:57 UTC, pzalep1 reviewed
Just that one addition to the cards and this should be good!

2021-09-01 19:18 UTC, pzalep1 approved these changes
MERGE!!!

2021-09-01 19:33 UTC, merged