Footer fix
Cyber4All/clark-client pull request #1266
Opened 2022-03-17 13:31 UTC by pzalep1

This PR fixes the footer issue.

2022-03-17 13:39 UTC, mfranz1 approved these changes

2022-03-17 13:54 UTC, EVogel1999 requested changes
Do you think we could move those logos out of that right align and center them in the footer?

2022-03-17 13:55 UTC, pzalep1 commented
> Do you think we could move those logos out of that right align and center them in the footer?

below all of the links?

2022-03-17 16:10 UTC, JosueMolinaMorales approved these changes

2022-03-17 20:16 UTC, EVogel1999 approved these changes

2022-03-18 11:40 UTC, StarChaser44 approved these changes

2022-03-21 14:18 UTC, merged