11502/add-relevancy-banner-to-details-page
Cyber4All/clark-client pull request #1334
Opened 2022-06-06 19:02 UTC by EVogel1999

Creates a banner on the details page for relevancy review.  Only displays when it is within a month of the nextCheck date.  URL is left blank till we know what the URL is in notion.  Completes story [11502/add-relevancy-banner-to-details-page](https://app.shortcut.com/clarkcan/story/11502/add-relevancy-banner-to-details-page).

2022-06-06 19:03 UTC, EVogel1999 commented
<img width="1678" alt="Screen Shot 2022-06-06 at 2 47 37 PM" src="https://user-images.githubusercontent.com/32078831/172229254-8a4d06e9-ee59-4b0c-914c-96e5fd30a635.png">

2022-06-06 19:27 UTC, AStoerkel1 approved these changes

2022-06-06 20:28 UTC, StarChaser44 approved these changes

2022-06-07 20:05 UTC, mfranz1 requested changes

2022-06-07 20:05 UTC, mfranz1 commented on src/app/cube/details/details.component.ts
> +  get relevancyBannerStatus(): boolean {
I would only display 1 month before relevancy and disappear only after relevancy has been updated

2022-06-08 16:19 UTC, mfranz1 commented on src/app/cube/details/details.component.html
> +      To learn more about our process for this review please read our <a href="">blog post</a>.
```suggestion
      To learn more about our process for this review please read our <a href="https://securedteam.notion.site/securedteam/Curriculum-Relevancy-on-CLARK-324ca3b482644068affe46c1ccbd28ff">blog post</a>.
```

2022-06-08 16:35 UTC, merged