Added message for empty notes section for a learning object
Cyber4All/clark-client pull request #1346
Opened 2022-06-10 13:29 UTC by StarChaser44

Replaces an empty box with a message denoting that a learning object does not have any notes if none exist.

2022-06-10 13:52 UTC, EVogel1999 approved these changes

2022-06-13 15:22 UTC, mfranz1 requested changes

2022-06-13 15:22 UTC, mfranz1 commented on src/app/cube/details/components/materials/components/notes/notes.component.ts
> +    if (!this.notes) {
This can be removed

2022-06-13 15:22 UTC, mfranz1 commented on src/app/cube/details/components/materials/components/notes/notes.component.html
> +  <p tab-index='0' [innerHtml]="notes">{{ notes }}</p>
```suggestion
  <p tab-index='0' >{{ notes ? notes: 'This Learning Object does not have any notes' }}</p>
```
The issue should have been the `[innerHtml]` pipe and accessing notes through {{notes}}. The pipe overrides the {{}} logic so by removing the pipe, the bracket logic will work.

2022-06-13 18:06 UTC, mfranz1 approved these changes

2022-06-14 12:55 UTC, pzalep1 approved these changes

2022-06-14 18:01 UTC, merged