Added description of missing fields to error message
Cyber4All/clark-client pull request #1378
Opened 2022-07-09 22:58 UTC by AStoerkel1

this PR completes [7667](https://app.shortcut.com/clarkcan/story/7667/add-message-for-missing-outcomes-contributors-or-description)

### This is what the error looks like from the submit component, which is used on the dashboard. The list changes depending on what is missing from the object:
<img width="710" alt="Screen Shot 2022-07-09 at 6 36 01 PM" src="https://user-images.githubusercontent.com/41537999/178125069-fa680831-e947-452f-82f9-e45547f7f8b1.png">

### This is the error the builder shows. This is persistent so it won't go away until the field is filled out:
<img width="841" alt="Screen Shot 2022-07-09 at 6 50 57 PM" src="https://user-images.githubusercontent.com/41537999/178125080-af13fd2f-2622-45b3-bf88-720bb7497aec.png">

2022-07-11 11:52 UTC, pzalep1 requested changes

2022-07-11 11:52 UTC, pzalep1 commented on src/app/onion/shared/submit/submit.component.ts
> +        `Missing Field(s):${missingFields}.`
```suggestion
        `Please provide the following fields to submit: ${missingFields}.`
```

2022-07-11 12:33 UTC, JosueMolinaMorales reviewed
Just Paige's change

2022-07-11 14:05 UTC, pmanal1 approved these changes

2022-07-11 14:21 UTC, mfranz1 approved these changes

2022-07-12 14:39 UTC, pzalep1 approved these changes

2022-07-12 14:58 UTC, merged