Implement mission section for Homepage Redesign
Cyber4All/clark-client pull request #1395
Opened 2022-07-27 14:26 UTC by pmanal1

Partially completes [12302](https://app.shortcut.com/clarkcan/story/12302/implement-hero-splash-and-mission-sections).

In this PR:
- Adds mobile and desktop views for the mission section.

## Screenshots

Desktop View
<img width="1440" alt="Screen Shot 2022-07-27 at 10 20 06 AM" src="https://user-images.githubusercontent.com/93054689/181271038-c369f763-7911-47b8-ba98-f38f9e7cc76a.png">

Mobile View
![mission mobile gif](https://user-images.githubusercontent.com/93054689/181272419-81b75477-e116-4cc2-998d-beb243885067.gif)

2022-07-28 14:57 UTC, EVogel1999 approved these changes

2022-07-28 16:00 UTC, pzalep1 reviewed
I will get you copy for this section as well.

2022-07-28 16:00 UTC, pzalep1 commented on src/app/cube/new-home/mission/mission.component.html
> +                Cursus euismod quis viverra nibh cras pulvinar.
I will get you copy for this as well.

2022-07-28 16:00 UTC, pzalep1 commented on src/app/cube/new-home/mission/mission.component.html
> +            <span class="fa-stack fa-2x">
Could change this class to be more descriptive?

2022-08-02 15:16 UTC, mfranz1 requested changes
COPY: https://docs.google.com/document/d/1bmTaQ-KjJc1kfdiy9Bh8EFWHQ6mUtSK7kh526YFpvjI/edit?usp=sharing

2022-08-02 18:05 UTC, pmanal1 commented
### Screenshot of new content text
<img width="1440" alt="Screen Shot 2022-08-02 at 2 04 45 PM" src="https://user-images.githubusercontent.com/93054689/182443399-77522801-0fa1-44b6-9d0a-1b3dea4be020.png">

2022-08-04 17:11 UTC, mfranz1 approved these changes

2022-08-05 18:13 UTC, pzalep1 approved these changes

2022-08-08 18:29 UTC, merged