Implementing Hierarchy Section for New Home Page
Cyber4All/clark-client pull request #1397
Opened 2022-07-29 18:32 UTC by jouypo23

This PR will be completing the requirements for [Story 12323](https://app.shortcut.com/clarkcan/story/12323/implement-learning-outcomes-and-hierarchies-sections).

2022-08-12 13:18 UTC, JosueMolinaMorales approved these changes

2022-08-12 14:03 UTC, EVogel1999 reviewed
Just one comment on lorem ipsum.  Looks good!

2022-08-12 14:03 UTC, EVogel1999 commented on src/app/cube/new-home/learning-object-info/hierarchies/hierarchies.component.html
> +    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris n
We need to replace the lorem ipsums with real descriptions.  I'd ask Paige or Mike about this.

2022-08-15 14:07 UTC, pmanal1 approved these changes

2022-08-15 16:43 UTC, pzalep1 approved these changes
This looks good, we can swap in the lorem ipsum later on after we get everything merged together.

2022-08-15 17:10 UTC, EVogel1999 approved these changes
After talking with Paige, the Lorem Ipsums will be replaced later.  Looks good!

2022-08-18 14:39 UTC, mfranz1 requested changes

2022-08-18 14:39 UTC, mfranz1 commented on src/app/cube/new-home/learning-object-info/hierarchies/hierarchies.component.ts
> +  @Input() length: 'nanomodule' | 'micromodule' | 'module' | 'unit' | 'course';
```suggestion
  length: 'nanomodule' | 'micromodule' | 'module' | 'unit' | 'course';
```
This variable isn't being dynamically set so we don't have to use the @Input decorator

2022-08-23 13:07 UTC, mfranz1 approved these changes
Nice work!

2022-08-23 13:45 UTC, merged