Add regex check
Cyber4All/clark-client pull request #1398
Opened 2022-08-01 13:10 UTC by JosueMolinaMorales

This PR completes [Add validation for special characters in Learning object names](https://app.shortcut.com/clarkcan/story/12712/add-validation-for-special-characters-in-learning-object-names)

The error message that appears when the user enters a special character:

<img width="1193" alt="Screen Shot 2022-07-29 at 2 09 38 PM" src="https://user-images.githubusercontent.com/72173743/182155280-bcd34025-6f62-4208-8aa6-83bab2c26f9b.png">

2022-08-01 13:55 UTC, pmanal1 approved these changes

2022-08-01 14:19 UTC, EVogel1999 approved these changes

2022-08-01 14:29 UTC, mfranz1 requested changes

2022-08-02 13:23 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +            'A learning object\'s name cannot contain a special character'
```suggestion
           e.message
```

2022-08-02 13:23 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +            'A learning object\'s name cannot contain a special character'
```suggestion
           e.message
```

2022-08-02 15:05 UTC, pzalep1 requested changes

2022-08-02 15:05 UTC, pzalep1 commented on src/entity/learning-object/error-messages.ts
> +  INVALID_CHARACTER_IN_NAME: 'Name cannot contain special characters',
Can we be more specific about the special characters not allowed?

2022-08-02 20:50 UTC, mfranz1 approved these changes

2022-08-03 17:51 UTC, merged