Animation Fixes for New Homepage
Cyber4All/clark-client pull request #1446
Opened 2022-08-30 19:38 UTC by pmanal1

Completes [13809](https://app.shortcut.com/clarkcan/story/13809/fix-animations-on-new-homepage).

In this PR:
- Fixes help component where leaving the view would result in the component overlapping with the splash
- Fixes mobile animation for the blogs component where the button would slide in before the rest of the component.

## Help Exit Animation
https://user-images.githubusercontent.com/93054689/187527064-93d904bf-074c-492e-942f-731af86cd3ba.mov
## Blogs Enter Animation (Mobile View)

https://user-images.githubusercontent.com/93054689/187527776-47585cb0-7479-4819-ae9e-14dbb3eae8f5.mov

2022-08-30 20:53 UTC, pzalep1 approved these changes

2022-08-31 13:02 UTC, AStoerkel1 requested changes

2022-08-31 13:02 UTC, AStoerkel1 commented on src/app/components/blogs/blogs.component.ts
> +    console.log(window.outerWidth < 1024, window.outerWidth);
console.log(:fire:)

2022-08-31 13:39 UTC, JosueMolinaMorales approved these changes

2022-08-31 14:23 UTC, AStoerkel1 approved these changes

2022-08-31 15:00 UTC, EVogel1999 approved these changes

2022-09-01 19:14 UTC, merged