chore: [sc-14590] Allow edit for authors on details page
Cyber4All/clark-client pull request #1480
Opened 2022-09-30 15:58 UTC by AStoerkel1

Story details: https://app.shortcut.com/clarkcan/story/14590

Authors can now edit from the details page until their object is released

Authors can no longer tag their own objects

"! Review Pending" no longer appears before the object is submitted for review

2022-09-30 16:10 UTC, EVogel1999 approved these changes

2022-10-03 15:09 UTC, mfranz1 requested changes
Good stuff; I would condense that one line

2022-10-04 13:04 UTC, JosueMolinaMorales approved these changes

2022-10-04 14:32 UTC, mfranz1 approved these changes
I will find all the nits to pick 😂

2022-10-04 17:03 UTC, pmanal1 approved these changes

2022-10-06 18:58 UTC, merged