added setSsoSession
Cyber4All/clark-client pull request #1486
Opened 2022-10-03 15:26 UTC by AStoerkel1

:fire::bug::fire:

2022-10-03 15:32 UTC, mfranz1 requested changes

2022-10-03 15:32 UTC, mfranz1 commented on src/app/clark.component.ts
> +    private cookies: CookieService
Not used

2022-10-03 15:32 UTC, mfranz1 commented on src/app/clark.component.ts
> +import { CookieService } from 'ngx-cookie-service';
Not used

2022-10-03 16:14 UTC, EVogel1999 reviewed
Just mike's comments.  Looks good otherwise!

2022-10-04 13:00 UTC, JosueMolinaMorales approved these changes

2022-10-04 14:29 UTC, mfranz1 approved these changes

2022-10-06 14:32 UTC, mfranz1 commented
Can you throw a patch version up

2022-10-06 17:20 UTC, merged