Bug/sc 16473/edit profile does not register existing input
Cyber4All/clark-client pull request #1572
Opened 2023-02-13 19:54 UTC by Maliyaa

BUG FIXED by creating an empty form group to allow the user info to be captured in the ngOnInit before validating for 'required'.

2023-02-14 13:44 UTC, JosueMolinaMorales reviewed
Looks good! Just the console log.

2023-02-14 13:44 UTC, JosueMolinaMorales commented on src/app/cube/user-profile/user-profile.component.ts
> +    console.log('yo');
Console log yo

2023-02-15 12:55 UTC, mfranz1 requested changes
Looks good! Just one change

2023-02-15 12:55 UTC, mfranz1 commented on src/app/core/auth-validation.service.ts
> +import { AbstractControl, AsyncValidatorFn, FormControl, FormGroup, Validators } from '@angular/forms';
```suggestion
import { FormControl, FormGroup, Validators } from '@angular/forms';
```
If these imports are not being used, lets delete them.

2023-02-15 15:24 UTC, pzalep1 reviewed
After the console is removed and the imports are fixed this will be good to go!

2023-02-16 15:02 UTC, mfranz1 approved these changes

2023-02-16 16:23 UTC, pzalep1 approved these changes

2023-02-17 14:44 UTC, Cwagne17 approved these changes

2023-02-17 14:48 UTC, JosueMolinaMorales approved these changes

2023-02-17 18:20 UTC, pmanal1 approved these changes

2023-02-20 17:48 UTC, merged