Implement an organization dropdown (only in registration)
Cyber4All/clark-client pull request #1616
Opened 2023-05-24 18:11 UTC by stef359

*I replaced the text field for the organization in the registration page with a drop down menu that includes all the organizations. 
*I could not replace the text field in edit-profile with the drop down because of an authorization bug.
*This is the third PR I created for this story because of previous issues so everything is from one commit.
<img width="584" alt="Screenshot 2023-05-24 at 10 30 29 AM" src="https://github.com/Cyber4All/clark-client/assets/92770851/86aff2b1-f38b-460d-97f0-a85c1ab81581">
<img width="695" alt="Screenshot 2023-05-24 at 10 31 19 AM" src="https://github.com/Cyber4All/clark-client/assets/92770851/e43c4d34-840b-485f-a2e7-1a70fce0d817">

2023-05-29 17:59 UTC, bereketsega reviewed
Looks good. Just one suggestion.

2023-05-29 17:59 UTC, bereketsega commented on src/app/auth/register/register.component.ts
> +  selectOrg(org?: Organization) {
It would be great if we have comment over this function.

2023-05-30 16:33 UTC, mfranz1 requested changes
You will also need to add `cardOrganizationUrl` to the `enviornonment.staging.ts`

2023-05-30 18:41 UTC, Cwagne17 approved these changes

2023-05-30 20:00 UTC, mfranz1 approved these changes

2023-05-31 13:19 UTC, merged