Feature/sc 23829/develop ncyte statistics dashboard
Cyber4All/clark-client pull request #1637
Opened 2023-07-14 15:48 UTC by pmanal1

[23829](https://app.shortcut.com/clarkcan/story/23829/develop-ncyte-statistics-dashboard)

Implements the NCyTE statistics dashboard.

Notes:
- The pie charts aren't implemented in this iteration. I didn't see a route that took statistics of bloom outcomes and learning object sizes by collection.

## Demo

https://github.com/Cyber4All/clark-client/assets/93054689/1025993d-7483-4d45-97a5-4a0d53899461

## Views

### Tablet

https://github.com/Cyber4All/clark-client/assets/93054689/f65ddbec-475e-48b7-906b-0af1687e474b

### 4K

https://github.com/Cyber4All/clark-client/assets/93054689/c86d2f47-ef07-4f1b-8792-8ec537f625a2

2023-07-14 17:54 UTC, bereketsega approved these changes
looks good

2023-07-14 18:18 UTC, mfranz1 approved these changes

2023-07-22 12:14 UTC, shanioffe approved these changes
Everything looks good, nice job!

2023-07-26 12:27 UTC, mfranz1 requested changes

2023-07-26 12:27 UTC, mfranz1 commented on src/environments/environment.prod.ts
> +  clarkReportsUrl: '',
This needs the production endpint

2023-07-26 12:32 UTC, mfranz1 requested changes

2023-07-26 12:32 UTC, mfranz1 commented on src/app/collection/collection.routing.ts
> +        component: NcyteDashboardComponent
Add curator guard

2023-07-26 12:33 UTC, mfranz1 requested changes

2023-07-26 12:33 UTC, mfranz1 commented on src/environments/route.ts
> +    let route = `${environment.clarkReportsUrl}?output=csv&collection=${collections.join(',')}`;
Route will need to be updated
```suggestion
    let route = `${environment.clarkReportsUrl}/reports?output=csv&collection=${collections.join(',')}`;
```

2023-08-29 15:46 UTC, mfranz1 commented on src/environments/environment.prod.ts
> +  clarkReportsUrl: '',
@JosueMolinaMorales can you grab this pls

2023-08-29 15:49 UTC, mfranz1 commented on src/environments/environment.prod.ts
> +  clarkReportsUrl: '',
Thank you @JosueMolinaMorales

2023-08-29 15:49 UTC, mfranz1 commented on src/environments/environment.prod.ts
> +  clarkReportsUrl: '',
https://b6il5p75bqszncpwtsqbgayewi0ganvt.lambda-url.us-east-1.on.aws/

2023-09-05 15:32 UTC, mfranz1 commented on src/environments/environment.staging.ts
> +  clarkReportsUrl: '',
```suggestion
```

2023-09-05 15:49 UTC, merged