Bug/sc 23904/remove plan c contribute button
Cyber4All/clark-client pull request #1642
Opened 2023-07-24 19:08 UTC by shanioffe

This PR fixes a bug where when a user visits the Plan C collection, any collections they may visit afterwards also show the contribute button.

Before:
https://github.com/Cyber4All/clark-client/assets/109975145/9bafab00-c766-4a2e-8915-d213aaacb272

After:
https://github.com/Cyber4All/clark-client/assets/109975145/256cb8d7-eb87-491e-9a20-72e9b9cb60d6

2023-07-25 12:17 UTC, mfranz1 requested changes

2023-07-25 12:17 UTC, mfranz1 commented on src/app/cube/collection-details/collection-details.component.ts
The story is to remove the button. We can disable is terminally by replacing lines 57 - 60 with just `this.showContribute = false;`. The button should not show at all. We can preserve the HTML code though if we chose to do something like this for a collection in the future

2023-07-25 15:38 UTC, bereketsega approved these changes
Just Mike's comment

2023-08-04 13:27 UTC, JosueMolinaMorales reviewed
Just mike's comment

2023-08-14 16:47 UTC, closed without merging