Feature/sc 25513/integrate organization dropdown component
Cyber4All/clark-client pull request #1659
Opened 2023-09-07 19:59 UTC by bereketsega

This PR adds organizations dropdown options component on `edit-profile` component.

## Demo

https://github.com/Cyber4All/clark-client/assets/72763770/a2c4c8c0-f8c7-40f5-885d-2d3613d26c4a

2023-09-07 20:11 UTC, stef359 approved these changes

2023-09-08 14:46 UTC, mfranz1 approved these changes
This looks good

2023-09-08 14:46 UTC, mfranz1 commented on src/app/core/interceptor/httpconfig.interceptor.ts
> +    if (!request.url.includes(environment.cardOrganizationUrl)) {
Nice

2023-09-08 14:46 UTC, mfranz1 commented on src/app/cube/user-profile/components/edit-profile/edit-profile.component.html
> +		(keyup)="keyup($event)"
nit pick can you tab this over

2023-09-08 18:40 UTC, shanioffe approved these changes

2023-09-11 13:17 UTC, JosueMolinaMorales approved these changes

2023-09-12 12:45 UTC, katieblomquist requested changes
Overall it looks pretty good! My only suggestion would be to make sure your dropdown is laying over the components below it rather than pushing them out of the way.

2023-09-12 17:43 UTC, bereketsega commented
> Overall it looks pretty good! My only suggestion would be to make sure your dropdown is laying over the components below it rather than pushing them out of the way.

**UPDATED**
<img width="757" alt="Screenshot 2023-09-12 at 1 36 12 PM" src="https://github.com/Cyber4All/clark-client/assets/72763770/e5980470-c083-40cb-864f-4bbe5585cbbb">

2023-09-15 16:51 UTC, katieblomquist approved these changes

2023-09-15 17:06 UTC, merged