Add browse button to secondary nav bar
Cyber4All/clark-client pull request #1670
Opened 2023-10-30 18:41 UTC by stef359

Added a Browse button on the nav bar.
<img width="952" alt="Screenshot 2023-10-30 at 2 29 31 PM" src="https://github.com/Cyber4All/clark-client/assets/92770851/85e324e9-29ce-48fe-8d55-0b833ed6a597">

2023-10-31 12:00 UTC, katieblomquist requested changes
My only comment is that Browse is the only CTA we have in the list, and should either be first or last. I would ask a higher power than myself as to which is preferred. Otherwise, this looks good!

2023-11-01 19:16 UTC, stef359 commented
The changes made to the header component file are from a previous task. I don't know why the changes are showing up on this branch even thought they were committed and pushed a while ago.

2023-11-02 14:57 UTC, Cwagne17 approved these changes

2023-11-03 14:14 UTC, shanioffe approved these changes

2023-11-06 14:36 UTC, bereketsega approved these changes

2023-11-06 15:13 UTC, merged