Feature/sc-27091/change-cc-4-0-checkbox-text
Cyber4All/clark-client pull request #1671
Opened 2023-11-07 14:20 UTC by bereketsega

This PR changes the checkbox text for creative commons license agreement.

2023-11-07 16:10 UTC, mfranz1 requested changes
Just a small wording change from page ;)

2023-11-07 16:10 UTC, mfranz1 commented on src/app/onion/shared/submit/submit.component.html
> +            <span tabindex="0" class="statement">By checking this box, I confirm that the materials for this Learning Object do not contain copyrighted materials and can
```suggestion
            <span tabindex="0" class="statement">By checking this box, I confirm that the materials for this Learning Object do not contain copyrighted content and can
```

2023-11-07 17:10 UTC, Cwagne17 approved these changes

2023-11-07 17:35 UTC, mfranz1 approved these changes

2023-11-09 13:42 UTC, JosueMolinaMorales approved these changes

2023-11-10 16:20 UTC, merged