Bug/sc 28033/add link to perform search on card
Cyber4All/clark-client pull request #1677
Opened 2024-01-05 19:30 UTC by ksmartin301

Added "Search on CARD" button for search queries to be directed to CARD website.

2024-01-08 15:51 UTC, mfranz1 requested changes
This also has changes from your editorial review process updates. These should be two different branches

2024-01-08 17:04 UTC, mfranz1 requested changes

2024-01-08 17:04 UTC, mfranz1 commented on src/app/admin/components/add-evaluator/components/object-dropdown/object-dropdown.component.ts
> +
```suggestion
```
Remove extra spacing

2024-01-08 17:04 UTC, mfranz1 commented on src/app/cube/browse/browse.component.html
> +          <a class="search-CARD" id="search-CARD" href="https://caeresource.directory/home/browse?q={{ query?.text }}" target=_blank *ngIf="query?.text !== '' || query.standardOutcomes.length">Search
```suggestion
          <a class="search-CARD" id="search-CARD" href="https://caeresource.directory/home/browse?q={{ query?.text }}" target=_blank *ngIf="query?.text !== '' ">Search with CARD</a>
```

2024-01-08 17:08 UTC, katieblomquist commented
Could you add screenshots of what the button on the page looks like as well as the resulting behavior?

2024-01-08 17:18 UTC, Cwagne17 approved these changes

2024-01-08 17:34 UTC, bereketsega approved these changes

2024-01-08 19:32 UTC, ksmartin301 commented
> Could you add screenshots of what the button on the page looks like as well as the resulting behavior?

![Link to CARD](https://github.com/Cyber4All/clark-client/assets/110073931/19cf7de0-2353-40f1-baf5-cb00d7496206)
![Search Page Results](https://github.com/Cyber4All/clark-client/assets/110073931/830b9329-360b-46ae-b000-0a9c7c103fb3)

2024-01-09 15:01 UTC, JosueMolinaMorales approved these changes

2024-01-10 15:33 UTC, mfranz1 reviewed
This is looking good, just curious, did Paige or anyone give guidance on the placement of the button? I wouldn't mind meeting to discuss this

2024-01-10 17:49 UTC, ksmartin301 reviewed
moved CARD search to the right side
![complie complete](https://github.com/Cyber4All/clark-client/assets/110073931/2a827790-913d-4f1b-94bf-6168254b767a)
![end page](https://github.com/Cyber4All/clark-client/assets/110073931/ddada5fc-41d4-471b-9bba-f3428dc77adb)

2024-01-10 18:16 UTC, mfranz1 reviewed
Perfect! One last thing, can you run `npm version minor` and push up that version patch? Then this will be good to deploy!

2024-01-10 18:36 UTC, mfranz1 approved these changes

2024-01-10 18:40 UTC, shanioffe approved these changes

2024-01-10 19:14 UTC, merged