Changes to clark client for implementing if a learning object has been submitted in clark-service
Cyber4All/clark-client pull request #1715
Opened 2024-04-17 12:59 UTC by johngonz0

This pr changes the old checkFirstSubmission routes in clark-client to reflect the changes I made in clark-service.

2024-04-17 14:25 UTC, Cwagne17 approved these changes

2024-04-18 17:43 UTC, mfranz1 commented on src/environments/route-copy.ts
We will eventually delete this file, can you revert these changes in this copy? This will help us debug incase we encounter any issues

2024-04-22 16:17 UTC, stef359 approved these changes

2024-04-25 13:28 UTC, JosueMolinaMorales approved these changes

2024-04-29 12:59 UTC, mfranz1 requested changes

2024-04-29 15:06 UTC, johngonz0 commented on src/app/core/learning-object-module/learning-object/learning-object.routes.ts
>      CHECK_FIRST_SUBMISSION(params: {
There was only 2 other instances of `CHECK_FIRST_SUBMISSION` in the client. One was in route.copy.ts which i reverted, and the other in Legacy Routes. I updated the params in the legacy route `CHECK_FIRST_SUBMISSION`. Is that all that is needed?

2024-04-29 15:24 UTC, mfranz1 approved these changes

2024-04-29 15:26 UTC, merged