Feature/sc 29053/implement getting a learning objects children
Cyber4All/clark-client pull request #1744
Opened 2024-06-11 15:45 UTC by curlyLasagna

Gets a learning-object's children. [Shortcut](https://app.shortcut.com/clarkcan/story/29053/implement-getting-a-learning-objects-children-in-clark-service)

Is it normal for the following animations to not be applied in service refactor?
`src/app/cube/details/components/splash/splash.component.ts`
```ts
@Component({
  selector: 'clark-details-splash',
  templateUrl: './splash.component.html',
  styleUrls: ['./splash.component.scss'],
  animations: [
    trigger('collection', [
      transition(':enter', [
        style({ opacity: 0, height: 0 }),
        animate('200ms ease', style({ opacity: 1, height: '*' }))
      ])
    ])
  ]
})
```

https://github.com/Cyber4All/clark-client/assets/44715649/dd2539c3-471e-41c8-9bda-fab71f90cd07

2024-06-12 00:42 UTC, johngonz0 commented on src/environments/route-copy.ts
You can actually leave this file unchanged. It is for reference purposes for old routes. I would just revert the changes you made.

2024-06-12 00:42 UTC, johngonz0 requested changes
looks great, just a comment about the route-copy.ts file

2024-06-12 12:27 UTC, JosueMolinaMorales approved these changes

2024-06-12 17:23 UTC, mfranz1 commented
> Is it normal for the following animations to not be applied in service refactor?

I'm not sure I understand. The animations are not firing? Or what's the issue?

2024-06-12 17:28 UTC, mfranz1 requested changes

2024-06-12 17:28 UTC, mfranz1 commented on src/app/admin/components/change-author/change-author.component.ts
> +    const childrenUri = `${environment.apiURL}/learning-objects/${encodeURIComponent(this.highlightedLearningObject.id)}/children`;
Import route from `src/app/core/learning-object-module/...`

2024-06-12 17:28 UTC, mfranz1 commented on src/app/core/learning-object-module/learning-object/learning-object.service.ts
> +    const childrenUri = `${environment.apiURL}/learning-objects/${encodeURIComponent(learningObjectId)}/children`;
Import route from `src/app/core/learning-object-module/...`

2024-06-12 17:28 UTC, mfranz1 commented on src/environments/route-copy.ts
+1, not critical but when we really get into testing this helps just identify any old routes we had

2024-06-12 18:02 UTC, curlyLasagna commented
> > Is it normal for the following animations to not be applied in service refactor?
> 
> I'm not sure I understand. The animations are not firing? Or what's the issue?

I should've specified that the video showed what I meant. When I click to make the sidebar appear with more details on the children in localhost, it doesn't apply the same animation as the one in production. Just wondering if it's normal

2024-06-12 19:05 UTC, johngonz0 approved these changes

2024-06-13 15:47 UTC, shanioffe approved these changes
Looks good!

2024-06-20 12:54 UTC, mfranz1 requested changes
Can you please fix the block comments in the routes

2024-06-20 12:54 UTC, mfranz1 commented on src/app/core/learning-object-module/learning-object/learning-object.routes.ts
> +    },
There's a block comment that belongs to the UPDATE_LEARNING_OBJECT_STATUS route function below. Can you please rearange and also create a block comment for this route. Just a generic description like the other block comment

2024-06-20 14:27 UTC, mfranz1 commented on src/app/core/learning-object-module/learning-object/learning-object.routes.ts
> +     * @param learningObjectID the id of the learning object
```suggestion
     * @param learningObjectID the id of the parent learning object
```

2024-06-20 14:58 UTC, mfranz1 approved these changes

2024-06-20 19:42 UTC, merged