Implement updates for getting collection metrics
Cyber4All/clark-client pull request #1746
Opened 2024-06-14 17:56 UTC by stef359

Client implementations for the updated response body of the GET-collection metrics route in CLARK-Service.

2024-06-17 21:02 UTC, johngonz0 approved these changes

2024-06-19 19:09 UTC, shanioffe approved these changes

2024-06-20 13:02 UTC, mfranz1 requested changes
All these collections have statistics. Please load your database and ensure those data values are returned to the client

2024-06-20 14:36 UTC, JosueMolinaMorales approved these changes

2024-06-21 12:37 UTC, curlyLasagna approved these changes

2024-07-15 19:02 UTC, mfranz1 approved these changes

2024-07-15 19:03 UTC, merged