Client changes for deleting outcome
Cyber4All/clark-client pull request #1755
Opened 2024-06-25 19:15 UTC by johngonz0

client changes help

2024-06-25 20:00 UTC, johngonz0 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +    this.outcomes.delete(outcome.serviceId);
```suggestion
    this.outcomes.delete(id);
```

2024-06-26 15:24 UTC, mfranz1 requested changes
yeah no

2024-06-26 15:24 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +    console.log(outcome);
```suggestion
```
🔥

2024-06-26 15:24 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +      console.log(newValue);
```suggestion
```
🔥

2024-06-26 15:24 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +        console.log(serviceId);
```suggestion
```
🔥

2024-06-26 15:24 UTC, mfranz1 commented on src/app/onion/learning-object-builder/components/outcome/outcome.component.ts
> +    console.log('emitting deletion');
```suggestion
```
🔥

2024-06-26 15:24 UTC, mfranz1 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +        console.log(outcome.serviceId);
```suggestion
```
🇧🇫

2024-06-26 15:24 UTC, mfranz1 commented on src/entity/learning-outcome/learning-outcome.ts
> +
Could these get a few inline or bloc comments?

2024-06-26 15:33 UTC, curlyLasagna approved these changes

2024-06-26 15:36 UTC, johngonz0 commented on src/app/onion/core/learning-object.service.ts
> +    console.log('here');
```suggestion
```

2024-06-26 15:36 UTC, johngonz0 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +    console.log(outcome);
```suggestion
```

2024-06-26 15:36 UTC, johngonz0 commented on src/app/onion/learning-object-builder/builder-store.service.ts
> +      console.log(newValue);
```suggestion
```

2024-06-26 18:00 UTC, stef359 approved these changes

2024-06-26 20:48 UTC, pzalep1 approved these changes

2024-06-27 13:59 UTC, mfranz1 approved these changes

2024-06-27 14:24 UTC, merged