'evaluation' correctional on editorial page
Cyber4All/clark-client pull request #1769
Opened 2024-07-11 09:53 UTC by ksmartin301

<img width="932" alt="Screenshot 2024-07-11 at 5 59 09 AM" src="https://github.com/Cyber4All/clark-client/assets/110073931/4f6cb775-8f82-4f0a-aefe-4183261bd082">
['evaluation' correctional on editorial page](https://github.com/Cyber4All/clark-client/pull/1769/commits/92529469ddf38095766034686d5602a789bbc542)

2024-07-11 11:19 UTC, curlyLasagna approved these changes

2024-07-11 11:48 UTC, pzalep1 requested changes

2024-07-11 11:48 UTC, pzalep1 commented on src/app/cube/content-pages/editorial-process/copy.ts
> +                        ' released on CLARK must comply with all of the characteristics mentioned in our evaluation procress. '
process too, not procress

2024-07-11 14:20 UTC, mfranz1 requested changes

2024-07-11 14:20 UTC, mfranz1 commented on src/app/cube/content-pages/editorial-process/copy.ts
> +                        ' released on CLARK must comply with all of the characteristics mentioned in our evaluation procress. '
```suggestion
                        ' released on CLARK must comply with all of the characteristics mentioned in our evaluation process. '
```

2024-07-13 22:50 UTC, johngonz0 approved these changes
Looks good, just page and mikes comments.

2024-07-15 13:08 UTC, stef359 commented
Mike and Paige's comments and it should be good

2024-07-15 13:08 UTC, stef359 approved these changes

2024-07-15 16:33 UTC, shanioffe approved these changes
Just the spell checks and you're good to go

2024-07-15 17:55 UTC, mfranz1 approved these changes

2024-07-16 13:02 UTC, pzalep1 approved these changes

2024-07-17 17:19 UTC, merged