Bug/sc 32292/adding contributors bug in builder
Cyber4All/clark-client pull request #1786
Opened 2024-07-23 16:20 UTC by johngonz0

Fix for adding contributors based off Khaleah's user entity id field update. transforms any id or _id received from service to userId for the client to use.

https://github.com/user-attachments/assets/32db80fc-44dc-4a5a-b50f-6bdaee76941a

2024-07-23 18:17 UTC, mfranz1 requested changes

2024-07-23 18:17 UTC, mfranz1 commented on src/app/core/user-module/user.service.ts
> +          user.userId = user._id;
Pls add just a small comment why we did this

2024-07-23 18:17 UTC, mfranz1 commented on src/app/core/user-module/user.service.ts
> +            user_res.userId = user_res._id;
here pls

2024-07-23 18:17 UTC, mfranz1 commented on src/entity/learning-object/learning-object.ts
> +      if(contributor.id) {
here too pls

2024-07-23 18:24 UTC, johngonz0 commented on src/entity/learning-object/learning-object.ts
> +    // when adding contributors, the id field can come back from the service as id or _id
```suggestion
    // when adding contributors, the original contributor id field can come back from the service as id or _id
```

2024-07-23 19:50 UTC, shanioffe approved these changes

2024-07-23 19:52 UTC, pzalep1 approved these changes

2024-07-23 23:20 UTC, stef359 approved these changes

2024-07-24 02:02 UTC, curlyLasagna approved these changes

2024-07-24 13:21 UTC, mfranz1 approved these changes

2024-07-24 15:07 UTC, merged