Client changes for other collection pages
Cyber4All/clark-client pull request #1799
Opened 2024-07-31 18:56 UTC by stef359

Sorry I focused only on the NCYTE page that I forgot to make necessary changes for the other collection pages,

**NICE:**
<img width="1424" alt="Screenshot 2024-07-31 at 9 31 57 PM" src="https://github.com/user-attachments/assets/9ed27f3c-2357-4d50-97fa-b35f623a88f6">

**502:**
<img width="833" alt="Screenshot 2024-07-31 at 9 54 57 PM" src="https://github.com/user-attachments/assets/77aef091-7ea3-402b-aa1c-692064b6f2f3">

**General collection pages:**
<img width="1401" alt="Screenshot 2024-07-31 at 9 47 10 PM" src="https://github.com/user-attachments/assets/47ee1b62-e9bf-46f6-aed9-64c788600fab">

2024-07-31 19:23 UTC, shanioffe commented on src/app/core/feature-module/featured.routes.ts
> +  * @param collectionAbvName the abbreviated name of the collection
Nit: add the limit param

2024-07-31 19:52 UTC, mfranz1 reviewed
Great Job! Thank you! I do have a requested change on your API that will fix the NCyTE collection card

2024-07-31 19:52 UTC, mfranz1 approved these changes

2024-07-31 20:13 UTC, shanioffe approved these changes

2024-07-31 20:41 UTC, pzalep1 commented
The NICE page is returning all featured learning objects not just the NICE Challenge ones.

2024-07-31 20:43 UTC, pzalep1 requested changes
Just the note about the NICE Challenge page.

2024-07-31 22:05 UTC, stef359 commented
@pzalep1 All the featured learning objects in the nice challenge page are confirmed nice-challenge learning objects. I just added a lot of them to the featured collection so I can test out the limit parameter being used by the route. Just had to make sure that if there were 7 nice objects in the featured collection only 6 would still show up.

2024-08-01 12:40 UTC, pzalep1 commented
> @pzalep1 All the featured learning objects in the nice challenge page are confirmed nice-challenge learning objects. I just added a lot of them to the featured collection so I can test out the limit parameter being used by the route. Just had to make sure that if there were 7 nice objects in the featured collection only 6 would still show up.

The Zero Trust learning objects in your screenshot are in the NCAE-C collection. Can you update that screenshot with the NICE objects to confirm?

2024-08-01 12:40 UTC, pzalep1 requested changes
Response to the screenshot.

2024-08-01 14:14 UTC, pzalep1 approved these changes

2024-08-01 15:14 UTC, curlyLasagna approved these changes

2024-08-02 16:16 UTC, mfranz1 approved these changes

2024-08-02 16:22 UTC, merged