Feature/sc 32777/revisions module route updates for clark
Cyber4All/clark-client pull request #1838
Opened 2024-08-30 18:50 UTC by Romerico234

2024-09-04 16:33 UTC, Cwagne17 reviewed
Rebase then re-request.

2024-09-04 17:30 UTC, pzalep1 requested changes

2024-09-04 17:30 UTC, pzalep1 commented on src/app/core/learning-object-module/revisions/revisions.service.ts
> +  }
The calls to all of these functions will also need to be updated in order to properly build the client.

2024-09-04 19:07 UTC, Romerico234 commented
Rebased and fixed the calls to the function

2024-09-09 13:04 UTC, pzalep1 approved these changes

2024-09-09 13:48 UTC, Cwagne17 commented on src/app/cube/details/components/action-panel/editorial-action-pad/editorial-action-pad.component.ts
>          this.router.navigate([`/onion/learning-object-builder/${this.revisedLearningObject.cuid}`]);
We may need to add the version as a query or path param to the router.navigate because cuid is shared across versions.

2024-09-09 13:53 UTC, Cwagne17 requested changes

2024-09-09 13:53 UTC, Cwagne17 commented on src/app/cube/details/components/action-panel/editorial-action-pad/editorial-action-pad.component.ts
>          this.revisedLearningObject = (await this.learningObjectServiceUri.fetchUri(revisionUri.revisionUri).toPromise())[0];
Can we add an inline comment TODO here to let us know to update the return value of createRevision to be the revised learning object rather then a URI that we just make a GET request directly after. (Essentially we are waisting time and requests by making a duplicate request that can be simplified by just returning the response that the client needs).

2024-09-09 15:16 UTC, Greek approved these changes
just nits, otherwise it looks good

2024-09-09 15:16 UTC, Greek commented on src/app/admin/components/learning-object-list-item/learning-object-list-item.component.ts
> +    private refactoredLearningObjectService: RefactoredLearningObjectService,
nit/debt: remove `refactoredLearningObjectService` and replace all instances of it with `loService`

2024-09-09 15:16 UTC, Greek commented on src/app/admin/core/unrelease.service.ts
> -
we could remove the entire file if this isn't needed

@Cwagne17 ?

2024-09-09 20:17 UTC, stef359 approved these changes

2024-09-10 13:17 UTC, Cwagne17 commented on src/app/cube/details/components/action-panel/editorial-action-pad/editorial-action-pad.component.ts
>          this.router.navigate([`/onion/learning-object-builder/${this.revisedLearningObject.cuid}`]);
+1

2024-09-10 18:34 UTC, Cwagne17 approved these changes

2024-09-11 00:51 UTC, merged